name: Push/PR

on:
  push:
    branches:
      - main
      - master
      - renovate/**
  pull_request:
  workflow_dispatch:

jobs:

  push-pr:
    uses: newrelic/coreint-automation/.github/workflows/reusable_push_pr.yaml@v3
    with:
      integration: statsd
      run_test_nix: false
      run_test_windows: false
      run_test_build_nix: false
      run_integration_nix: false
    secrets: inherit

  integration-test:
    name: 🚧 integration tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [  arm64, amd64 ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.OHAI_DOCKER_HUB_ID }}
          password: ${{ secrets.OHAI_DOCKER_HUB_PASSWORD }}

      - name: Running integration tests
        run: |
          make integration-tests-${{ matrix.arch }}